In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
df=pd.read_csv("https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv")

In [ ]:
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [ ]:
df.variety.value_counts()

Setosa        50
Versicolor    50
Virginica     50
Name: variety, dtype: int64

In [ ]:
x=df.drop(['variety'],axis=1)
y=df['variety']

In [ ]:
x.head()

sepal.length  sepal.width  petal.length  petal.width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2, random_state = 30)
print("Training, Testing and Splitting is successful")

Training, Testing and Splitting is successful


In [ ]:
 from sklearn.naive_bayes import GaussianNB
 gnb = GaussianNB()
 gnb.fit(X_train, Y_train)

GaussianNB()

In [ ]:
print("Training Accuracy:", gnb.score(X_train, Y_train)*100)

Training Accuracy: 96.66666666666667


In [ ]:
Y_predict = gnb.predict(X_test)
print("Testing Accuracy:", gnb.score(X_test, Y_test)*100)

Testing Accuracy: 93.33333333333333


In [ ]:
from sklearn.metrics import accuracy_score
Acc = accuracy_score(Y_test, Y_predict)
print(Acc)

0.9333333333333333


In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_predict)
print(cm)

[[12  0  0]
 [ 0  8  1]
 [ 0  1  8]]
